spring:
  application:
    name: microservices
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_boot_app
    username: root
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27117
      database: microservice
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  profiles: development